spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ingredient
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/ingredients
        - id: basket
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/basket/**
        - id: recipe
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/recipes/**
server:
  port: 8222