spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ingredient
          uri: http://localhost:8082
          predicates:
            - Path=/ingredients
        - id: basket
          uri: http://localhost:8083
          predicates:
            - Path=/basket/**
        - id: recipe
          uri: http://localhost:8084
          predicates:
            - Path=/recipe/**
server:
  port: 8222